engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
  markdownlint:
    enabled: true
  scss-lint:
    enabled: true
ratings:
  paths:
  - "**.js"
  - "**.md"
  - "**.scss"
